### ISSUE TITLE
Expired tokens removed before refresh can happen

### ISSUE THREAD

**Issue by jamescoletti** [reneweb/oauth2orize_resource_owner_password_example#1]
Thanks for posting this example.

I believe the implementation is slightly broken.

Attempting to authenticate with an expired access token causes it to be removed from the server:
https://github.com/reneweb/oauth2orize_resource_owner_password_example/blob/430deec5554ff0c3eed9a001decea2339bd616d0/auth.js#L50

When a client then attempts to obtain a new access token using a refresh token, the original access token no longer exists for updating and thus authentication fails:
https://github.com/reneweb/oauth2orize_resource_owner_password_example/blob/430deec5554ff0c3eed9a001decea2339bd616d0/oauth.js#L51

**Comment by reneweb** [comment]
Hey,
I realize that this issue is very old. I never got notified and just looked randomly at my old projects on github and saw the issue. Yeah, you are right this is indeed a problem and thanks for pointing it out. 
I changed the code to not remove the access token when it is expired so the update will succeed (https://github.com/reneweb/oauth2orize_resource_owner_password_example/blob/master/auth.js#L50). It should also be possible to upsert the access token entry instead of doing an update.
